export const FETCH_FMS_START = 'FETCH_FMS_START';
export const FETCH_FMS_ERROR = 'FETCH_FMS_ERROR';
export const FETCH_FMS_SUCCESS = 'FETCH_FMS_SUCCESS';

export const DEMO_FORM_SUBMIT = 'DEMO_FORM_SUBMIT';
export const DEMO_FORM_LOAD = 'DEMO_FORM_LOAD';
