export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const DEMO_FORM_SUBMIT = 'DEMO_FORM_SUBMIT';
export const DEMO_FORM_LOAD = 'DEMO_FORM_LOAD';
